mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.pojo

logging:
 level:
  com: debug




spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.36.229:3306/myWeChatDataBase?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: A8945984$
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
      database : MYSQL
      show-sql : true
      hibernate:
        ddl-auto : update
        naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect : org.hibernate.dialect.MySQL5Dialect








